version: '3'

services:
  php:
    build: ./docker/php
    volumes:
       - ./html:/var/www/html
    ports:
       - 8080:80
    links:
       - memcached
  memcached:
    image: memcached:1.4

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
       - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=test
      - PMA_PASSWORD=test

    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

  